ALTER TABLE RAUSHAN.USER_DETAILS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RAUSHAN.USER_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.USER_DETAILS
(
  USER_ID             VARCHAR2(5 BYTE)          NOT NULL,
  FIRST_NAME          VARCHAR2(200 BYTE)        NOT NULL,
  LAST_NAME           VARCHAR2(200 BYTE),
  DATE_OF_BIRTH       DATE,
  USER_GENDER         VARCHAR2(10 BYTE),
  USER_OCCUPATION     VARCHAR2(10 BYTE),
  PHONE_NO            NUMBER(10)                NOT NULL,
  EMAIL_ID            VARCHAR2(200 BYTE),
  USER_RATING         NUMBER(5,3),
  AREA                VARCHAR2(200 BYTE),
  CITY                VARCHAR2(200 BYTE),
  ZIP_CODE            VARCHAR2(200 BYTE),
  COUNTRY             VARCHAR2(200 BYTE),
  CREATED_DATE        DATE,
  CREATED_BY          VARCHAR2(200 BYTE),
  LAST_MODIFIED_BY    VARCHAR2(200 BYTE),
  LAST_MODIFIED_DATE  DATE,
  USER_ORGANIZATION   VARCHAR2(1000 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RAUSHAN.USER_DETAILS ADD (
  PRIMARY KEY
 (USER_ID)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

			   
/************/

ALTER TABLE RAUSHAN.USER_LOGIN
 DROP PRIMARY KEY CASCADE;
DROP TABLE RAUSHAN.USER_LOGIN CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.USER_LOGIN
(
  USER_ID             VARCHAR2(5 BYTE)          NOT NULL,
  PASS                VARCHAR2(200 BYTE)        NOT NULL,
  STATUS              VARCHAR2(200 BYTE),
  CREATED_DATE        DATE                      DEFAULT SYSDATE,
  LAST_MODIFIED_DATE  DATE
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RAUSHAN.USER_PK1 ON RAUSHAN.USER_LOGIN
(USER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RAUSHAN.USER_LOGIN ADD (
  CONSTRAINT USER_PK1
 PRIMARY KEY
 (USER_ID)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE RAUSHAN.USER_LOGIN ADD (
  CONSTRAINT USER_FK 
 FOREIGN KEY (USER_ID) 
 REFERENCES RAUSHAN.USER_DETAILS (USER_ID));

/**********************/

 ALTER TABLE RAUSHAN.REQUEST_DETAILS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RAUSHAN.REQUEST_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.REQUEST_DETAILS
(
  REQUEST_ID       VARCHAR2(5 BYTE)             NOT NULL,
  USER_ID          VARCHAR2(5 BYTE),
  USER_NAME        VARCHAR2(1000 BYTE),
  USER_MOBILE      VARCHAR2(10 BYTE),
  USER_EMAIL       VARCHAR2(30 BYTE),
  ZIP_CODE         VARCHAR2(30 BYTE),
  REQUEST_DESC     VARCHAR2(4000 BYTE),
  CATEGORY_ID      VARCHAR2(100 BYTE),
  SUB_CATEGORY_ID  VARCHAR2(200 BYTE),
  AUTH_FLAG        VARCHAR2(3 BYTE),
  STATUS           VARCHAR2(10 BYTE),
  SUPPORT_COUNT    VARCHAR2(200 BYTE),
  REQ_RATING       VARCHAR2(200 BYTE),
  COMPLAIN_FLAG    VARCHAR2(1 BYTE)             DEFAULT 0,
  DISPLAY_FLAG     VARCHAR2(1 BYTE)             DEFAULT 0,
  POST_DATE        DATE
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RAUSHAN.REQUEST_DETAILS ADD (
  PRIMARY KEY
 (REQUEST_ID)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

			   /**************/
			   
ALTER TABLE RAUSHAN.USER_ATTACHMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RAUSHAN.USER_ATTACHMENTS CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.USER_ATTACHMENTS
(
  ATTACHMENT_ID    VARCHAR2(10 BYTE)            NOT NULL,
  USER_ID          VARCHAR2(1000 BYTE),
  REQUEST_ID       VARCHAR2(1000 BYTE),
  COMMENTS_ID      VARCHAR2(1000 BYTE),
  ATTACHMENT_PATH  VARCHAR2(4000 BYTE),
  STATUS           VARCHAR2(10 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RAUSHAN.USER_ATTACHMENTS ADD (
  PRIMARY KEY
 (ATTACHMENT_ID)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE RAUSHAN.USER_ATTACHMENTS ADD (
  CONSTRAINT USER_FK3 
 FOREIGN KEY (USER_ID) 
 REFERENCES RAUSHAN.USER_DETAILS (USER_ID));

/******************/

ALTER TABLE RAUSHAN.REQ_CATEGORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE RAUSHAN.REQ_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.REQ_CATEGORY
(
  CATEGORY_ID    VARCHAR2(1000 BYTE)            NOT NULL,
  CATEGORY_NAME  VARCHAR2(1000 BYTE),
  CATEGORY_RANK  VARCHAR2(1000 BYTE),
  STATUS         VARCHAR2(10 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RAUSHAN.REQ_CATEGORY ADD (
  PRIMARY KEY
 (CATEGORY_ID)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

/***************/

ALTER TABLE RAUSHAN.USER_COMMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE RAUSHAN.USER_COMMENTS CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.USER_COMMENTS
(
  COMMENTS_ID    VARCHAR2(10 BYTE)              NOT NULL,
  USER_ID        VARCHAR2(1000 BYTE),
  REQUEST_ID     VARCHAR2(1000 BYTE),
  COMMENTS_DESC  VARCHAR2(4000 BYTE),
  STATUS         VARCHAR2(10 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RAUSHAN.USER_COMMENTS ADD (
  PRIMARY KEY
 (COMMENTS_ID)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE RAUSHAN.USER_COMMENTS ADD (
  CONSTRAINT USER_FK4 
 FOREIGN KEY (USER_ID) 
 REFERENCES RAUSHAN.USER_DETAILS (USER_ID));

/*************/
 ALTER TABLE RAUSHAN.REQ_SUB_CATEGORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE RAUSHAN.REQ_SUB_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.REQ_SUB_CATEGORY
(
  SUB_CATEGORY_ID    VARCHAR2(1000 BYTE)        NOT NULL,
  CATEGORY_ID        VARCHAR2(1000 BYTE),
  SUB_CATEGORY_NAME  VARCHAR2(1000 BYTE),
  SUB_CATEGORY_RANK  VARCHAR2(1000 BYTE),
  STATUS             VARCHAR2(10 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE RAUSHAN.REQ_SUB_CATEGORY ADD (
  PRIMARY KEY
 (SUB_CATEGORY_ID)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE RAUSHAN.REQ_SUB_CATEGORY ADD (
  CONSTRAINT USER_FK5 
 FOREIGN KEY (CATEGORY_ID) 
 REFERENCES RAUSHAN.REQ_CATEGORY (CATEGORY_ID));

 /*******************/
 DROP TABLE RAUSHAN.USER_LOGIN_DATA CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.USER_LOGIN_DATA
(
  USER_ID      VARCHAR2(5 BYTE),
  LOGIN_TIME   DATE                             DEFAULT SYSDATE,
  LOGOUT_TIME  DATE,
  STATUS       VARCHAR2(200 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER RAUSHAN.LOGIN_HIST_TRI
AFTER INSERT OR UPDATE ON RAUSHAN.USER_LOGIN_DATA FOR EACH ROW
BEGIN

 IF INSERTING THEN 
 
 INSERT INTO USER_LOGIN_DATA_HISTORY (USER_ID,LOGIN_TIME,LOGOUT_TIME,IP_ADDRESS)
 VALUES (:NEW.USER_ID,SYSDATE,NULL,NULL); 
 
 
 END IF;
 
 IF UPDATING THEN
 
 UPDATE USER_LOGIN_DATA_HISTORY SET LOGOUT_TIME=:NEW.LOGOUT_TIME,IP_ADDRESS='10.12.45.16', STATUS='ACTIVE'
 WHERE USER_ID=:OLD.USER_ID AND LOGOUT_TIME IS NULL;
 
 END IF;
 
END ;
/

/****************/

DROP TABLE RAUSHAN.USER_LOGIN_DATA_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE RAUSHAN.USER_LOGIN_DATA_HISTORY
(
  USER_ID      VARCHAR2(5 BYTE),
  LOGIN_TIME   DATE                             DEFAULT SYSDATE,
  LOGOUT_TIME  DATE                             DEFAULT SYSDATE,
  STATUS       VARCHAR2(200 BYTE),
  IP_ADDRESS   VARCHAR2(50 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

